### ISSUE TITLE
Error in on_train_end event when training AdapterFusion with load_best_model_at_end enabled

### ISSUE THREAD

**Issue by ReneEmmaneel** [adapter-hub/adapter-transformers#338]
## Information

When training an adapter fusion model with load_best_model_at_end=True as argument, the code gives an error after the on_train_end event is called. I am using the bert-base-uncased on the pfeiffer architecture with preloaded task adapters.

## To reproduce

1. Add load_best_model_at_end=True to the arguments

```
training_args = TrainingArguments(
    learning_rate=5e-5,
    num_train_epochs=10,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    output_dir="training_output",
    overwrite_output_dir=True,
    load_best_model_at_end=True,
    remove_unused_columns=False,
)
```
 
2. Train adapter fusion model

```
model.train_adapter_fusion(adapter_setup)
trainer = AdapterTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    compute_metrics=compute_accuracy,
)
trainer.train()
```

Error message:

```
Traceback (most recent call last):
  File "/home/lcur1191/project/adapter_fusion.py", line 102, in <module>
    train_model(model, training_args, dataset)
  File "/home/lcur1191/project/adapter_fusion.py", line 71, in train_model
    trainer.train()
  File "/home/lcur1191/.conda/envs/ATCS/lib/python3.9/site-packages/transformer$
    self.control = self.callback_handler.on_train_end(args, self.state, self.co$
  File "/home/lcur1191/.conda/envs/ATCS/lib/python3.9/site-packages/transformer$
    return self.call_event("on_train_end", args, state, control)
  File "/home/lcur1191/.conda/envs/ATCS/lib/python3.9/site-packages/transformer$
    result = getattr(callback, event)(
  File "/home/lcur1191/.conda/envs/ATCS/lib/python3.9/site-packages/transformer$
    fusion_models = getattr(self.model.config, "adapter_fusion_models", [])
AttributeError: 'AdapterTrainerCallback' object has no attribute 'model'
```

Relevant code from src/transformers/adapters/trainer.py

```
model = kwargs.pop("model")
...
fusion_models = getattr(self.model.config, "adapter_fusion_models", [])
for fusion in fusion_models:
    fusion_dir = os.path.join(state.best_model_checkpoint, fusion)
    if os.path.exists(fusion_dir):
        self.model.load_adapter_fusion(fusion_dir)
```

## Expected behaviour

It is my understanding that the correct behaviour would be that the adapter fusion in my setup would correctly load at the end. I believe that 'self.model' should be changed to 'model' twice in the trainer.py file, given that model is given as input to the on_train_end event, and AdapterTrainerCallback.model is not defined. My question is if my understanding about this is correct?

**Comment by calpt** [comment]
Hey @ReneEmmaneel, thanks for bringing this up. This is indeed an issue with our implementation. Should be fixed by #341.
