### ISSUE TITLE
Running the RoBERTa model shows errors on GLUE with adapters.

### ISSUE THREAD

**Issue by hanzhou032** [adapter-hub/adapter-transformers#453]
## Environment info

- `adapter-transformers` version: 3.1.0
- Platform: ubuntu 20.04
- Python version: 3.8.13
- Huggingface_hub version: 0.7.0
- PyTorch version (GPU?): 1.12.0 (True)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

Model I am using (Bert, XLNet ...): RoBERTa

Language I am using the model on (English, Chinese ...): English

Adapter setup I am using (if any): pfeiffer 

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)
export TASK_NAME=mrpc

python run_glue.py \
  --model_name_or_path roberta-base \
  --task_name $TASK_NAME \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 1e-4 \
  --num_train_epochs 10.0 \
  --output_dir /tmp/$TASK_NAME \
  --overwrite_output_dir \
  --train_adapter \
  --adapter_config pfeiffer

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (GLUE)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Install adapter-transformers 3.1.0
2. Install requirements for text classification
3. Run the above script for roberta-base on GLUE with the Pfeiffer adapter.

     Traceback (most recent call last):
  File "run_glue.py", line 677, in <module>
    main()
  File "run_glue.py", line 589, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/trainer.py", line 1498, in train
    return inner_training_loop(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/trainer.py", line 1740, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/trainer.py", line 2470, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/trainer.py", line 2502, in compute_loss
    outputs = model(**inputs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/adapters/models/roberta/adapter_model.py", line 68, in forward
    outputs = self.roberta(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/adapters/context.py", line 108, in wrapper_func
    results = f(self, *args, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 879, in forward
    encoder_outputs = self.encoder(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 548, in forward
    layer_outputs = layer_module(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 433, in forward
    self_attention_outputs = self.attention(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 357, in forward
    self_outputs = self.self(
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/models/roberta/modeling_roberta.py", line 212, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/adapter/lib/python3.8/site-packages/transformers/adapters/lora.py", line 251, in forward
    return F.linear(x, T(self.weight), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

## Expected behavior

BERT, mBERT, BERT-large works well in the settings. However, RoBERTa and XLM-R have this error that I cannot fix it.
Thanks a lot for your help.

**Comment by hSterz** [comment]
Hey, unfortunately, I was unable to reproduce this error (see this [colab notebook](https://colab.research.google.com/drive/1P_vm00AyCyDMUTz9Rg-KD-eZkc1xcw0Z?usp=sharing)). So I am not sure what the problem is you're facing. Things you could check are:
- Does your cuda version work with your pytorch version?
- You can try a smaller batch size to rule out that a memory problem causes this.

I hope this helps.
